export type LeaderLevel = 'ic' | 'team_lead' | 'manager' | 'director' | 'executive';

export interface ChecklistItemDef {
  id: string;
  title: string;
  description: string;
  detail: string;
  phase: 1 | 2 | 3;
  default_week: number;
  default_day?: number;
  category: string;
  priority: 'critical' | 'high' | 'normal';
  relevant_levels?: LeaderLevel[];
  start_week: number;
  end_week: number;
  watkins_groups: string[];
  parent_id?: string;
  depth: number;
  sub_activity?: string;
}

export const CHECKLIST_ITEMS: ChecklistItemDef[] = [

  // ─── GROUP 1: PREPARE YOURSELF ────────────────────────────────────────────

  {
    id: 'group-prepare',
    title: 'Prepare Yourself',
    description: 'Everything that can be done before Day 1 — no access, no authority, no insider knowledge needed.',
    detail: 'Invest here to maximise cognitive bandwidth from the start. Preparation compounds — every hour invested here saves days later.',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'critical',
    start_week: 0,
    end_week: 2,
    watkins_groups: ['Prepare Yourself'],
    depth: 0,
  },
  {
    id: 'financials-review',
    title: 'Get financials, review website and other information on strategy, products and brands',
    description: 'Build a picture from public sources before you have insider access.',
    detail: 'Review the organisation\'s annual report, public strategy documents, recent press coverage, and website. Look for stated priorities, financial performance trends, product/service mix, and how the organisation presents itself publicly. Note gaps between public narrative and what you hear informally. This is your baseline before insider access colours your view.',
    phase: 1,
    default_week: 0,
    category: 'Strategy',
    priority: 'critical',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Accelerate Your Learning'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'contacts-prestart',
    title: 'Speak to key internal and external contacts in advance',
    description: 'Use your existing network to get ahead of insider knowledge before Day 1.',
    detail: 'Reach out to people you already know inside or adjacent to the organisation. Ask open questions: What should I know before I start? Who are the key people I need to meet? What are the landmines? What\'s the mood? Keep these conversations informal — you\'re listening, not signalling. Also reach out to external contacts in the sector for an outside-in perspective.',
    phase: 1,
    default_week: 0,
    category: 'Relationships',
    priority: 'high',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'calendar-control',
    title: 'Take control of your calendar',
    description: 'Set the rhythm you want before others set it for you.',
    detail: 'Before Day 1, block time for the structured activities you know you\'ll need: listening tour 1:1s, weekly reviews, monthly check-ins with boss, and protected thinking time. Don\'t let your first weeks fill up with reactive meetings. Set the rhythm you want before others set it for you.',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'high',
    start_week: 0,
    end_week: 1,
    watkins_groups: ['Prepare Yourself', 'Manage Yourself'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'schedule-early-meetings',
    title: 'Schedule early meetings for relationship building',
    description: 'Book all key introductory meetings before Day 1 where possible.',
    detail: 'The goal of these early meetings is relationship-building, not diagnosis (that comes later). Show up curious. Ask about them, their work, what they care about. You\'re establishing trust and psychological safety before you start asking hard questions.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 0,
    end_week: 2,
    watkins_groups: ['Prepare Yourself', 'Negotiate Success'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'schedule-direct-reports',
    title: 'Schedule early meetings — direct reports',
    description: 'Book 1:1s with each direct report in weeks 0–1.',
    detail: 'Schedule 1:1 introductory meetings with each of your direct reports in weeks 0–1. The goal is relationship-building — show up curious and ask about them, their work, what they care about.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 0,
    end_week: 1,
    watkins_groups: ['Prepare Yourself', 'Negotiate Success'],
    parent_id: 'schedule-early-meetings',
    depth: 1,
  },
  {
    id: 'schedule-line-manager',
    title: 'Schedule early meetings — line manager',
    description: 'Book introductory 1:1 with your line manager in weeks 0–1.',
    detail: 'Schedule an early 1:1 with your line manager — focus on relationship-building. Show up curious. Understand how they prefer to work and what they\'re hoping for from you.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 0,
    end_week: 1,
    watkins_groups: ['Prepare Yourself', 'Negotiate Success'],
    parent_id: 'schedule-early-meetings',
    depth: 1,
  },
  {
    id: 'schedule-peers',
    title: 'Schedule early meetings — peers',
    description: 'Book introductory meetings with peer leaders in weeks 0–1.',
    detail: 'Schedule early introductory meetings with key peers — other directors, heads of department, or equivalents. Don\'t wait for them to come to you.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'high',
    start_week: 0,
    end_week: 1,
    watkins_groups: ['Prepare Yourself', 'Create Alliances'],
    parent_id: 'schedule-early-meetings',
    depth: 1,
  },
  {
    id: 'schedule-wider-team',
    title: 'Schedule early meetings — wider direct team',
    description: 'Book introductory meetings with your wider direct team in weeks 0–2.',
    detail: 'Schedule meetings with your wider direct team beyond direct reports. Build connection and begin understanding team culture and morale from the ground level.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'high',
    start_week: 0,
    end_week: 2,
    watkins_groups: ['Prepare Yourself', 'Build Your Team'],
    parent_id: 'schedule-early-meetings',
    depth: 1,
  },
  {
    id: 'schedule-enabling-colleagues',
    title: 'Schedule early meetings — key enabling colleagues',
    description: 'Book introductory meetings with key enabling colleagues across the organisation in weeks 0–2.',
    detail: 'Schedule meetings with the people outside your direct team who enable your team to function — finance, HR, IT, legal, communications, central strategy. Build relationships before you need something.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'high',
    start_week: 0,
    end_week: 2,
    watkins_groups: ['Prepare Yourself', 'Create Alliances'],
    parent_id: 'schedule-early-meetings',
    depth: 1,
  },
  {
    id: 'work-preferences',
    title: 'Assess your work preferences and identify problem areas',
    description: 'Create a self-assessment grid to identify where you may have blind spots.',
    detail: 'Create a self-assessment grid. List your key tasks and responsibilities, then classify each as: Technical, Relationships/Political, or Cultural. Score your preference for each type of task out of 10. Identify where your natural preferences may create blind spots — e.g. if you score low on political tasks but your role requires significant stakeholder navigation. This isn\'t about changing who you are; it\'s about knowing where to be intentional.',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'high',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Manage Yourself'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'it-practicalities',
    title: 'Ensure you have IT, pension, phone, business cards, and other practicalities sorted',
    description: 'Chase HR/IT before Day 1 — resolve all admin friction in week 1.',
    detail: 'Chase HR/IT before Day 1 if possible: laptop, system access, email, phone, security passes. Confirm pension enrolment, payroll setup, expense system access. Have business cards ordered. These feel trivial but unresolved admin creates friction and sends signals. Get it done in week 1 at the latest.',
    phase: 1,
    default_week: 1,
    category: 'Process',
    priority: 'normal',
    start_week: 0,
    end_week: 1,
    watkins_groups: ['Prepare Yourself'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'stakeholder-map-internal',
    title: 'Map key stakeholders — internal',
    description: 'Begin building a map of the internal landscape.',
    detail: 'Begin building a stakeholder map of internal players. For each person note: their role, their relationship to your team/work, their likely attitude to you (supporter/neutral/resistant), and their influence. You\'ll refine this over time. Use the People tab in this app to track individuals.',
    phase: 1,
    default_week: 2,
    category: 'Relationships',
    priority: 'high',
    start_week: 1,
    end_week: 3,
    watkins_groups: ['Prepare Yourself', 'Create Alliances'],
    parent_id: 'group-prepare',
    depth: 1,
  },
  {
    id: 'stakeholder-map-external',
    title: 'Map key stakeholders — external',
    description: 'Identify and begin mapping the key external stakeholders who matter to your team\'s success.',
    detail: 'Identify the key external stakeholders — clients, funders, partners, regulators, sector bodies — who matter to your team\'s success. For a senior role, external relationships often define your ability to deliver. Map their interests, their influence, and the current state of the relationship. Start scheduling meetings in weeks 3–5.',
    phase: 1,
    default_week: 3,
    category: 'Relationships',
    priority: 'high',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Prepare Yourself', 'Create Alliances'],
    parent_id: 'group-prepare',
    depth: 1,
  },

  // ─── GROUP 2: ACCELERATE YOUR LEARNING ───────────────────────────────────

  {
    id: 'group-learning',
    title: 'Accelerate Your Learning',
    description: 'Structured learning is the foundation of everything that follows.',
    detail: 'The goal in weeks 1–5 is to build a comprehensive, evidence-based picture of the organisation, team, and environment — across both hard data and soft signals.',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 7,
    watkins_groups: ['Accelerate Your Learning'],
    depth: 0,
  },

  // Section A: General Orientation
  {
    id: 'basic-orientation',
    title: 'Basic orientation',
    description: 'Get the basics in your first days — facilities, people, informal rhythms.',
    detail: 'In your first days, get the basics: where things are, how facilities work, who the key support staff are (EA, IT, facilities, HR). Learn the informal rhythms — when people eat lunch, which meetings are sacred, the unwritten norms. This feels trivial but getting it wrong creates friction and signals poor awareness.',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'high',
    start_week: 1,
    end_week: 1,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'core-systems',
    title: 'Core systems',
    description: 'Get set up and functional on every system you\'ll need in the first month.',
    detail: 'Get set up and functional on every system you\'ll need in the first month. Don\'t wait to be shown — ask IT/HR proactively. Understanding the expense system on week 5 when you have a backlog is painful and avoidable. Key systems: HR system (leave, performance management), financials, expenses.',
    phase: 1,
    default_week: 1,
    category: 'Process',
    priority: 'high',
    start_week: 1,
    end_week: 1,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'financials-deep-dive',
    title: 'Financials deep-dive',
    description: 'Go beyond public financials to internal budget vs actuals and team P&L.',
    detail: 'Go beyond the public-facing financials you reviewed pre-start. Get access to internal financial reports: budget vs actuals for your team, headcount costs, project financials if applicable. Understand how the organisation measures financial performance and what your team\'s P&L or budget responsibility looks like.',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'performance-management-system',
    title: 'Performance management',
    description: 'Understand how performance is managed — formally and informally.',
    detail: 'Understand how performance is managed in the organisation. What\'s the review cycle? What does good performance look like formally vs informally? What are the incentive structures? Are people rewarded for the right behaviours? This will inform your team assessment.',
    phase: 1,
    default_week: 1,
    category: 'Process',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'strategies-operating-plans',
    title: 'Strategies and operating plans',
    description: 'Read the current strategy and operating plan critically.',
    detail: 'Get access to the current strategy documents, operating plan, and any OKRs or KPIs your team is accountable for. Read them critically: is this the real strategy or the stated strategy? Is the team actually pursuing it? What\'s the gap between plan and reality?',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'personnel-data',
    title: 'Personnel data',
    description: 'Get the team\'s personnel data as input to your team assessment.',
    detail: 'Get the team\'s personnel data: job titles, grades, tenure, performance ratings, salary bands where accessible. Who has been here longest? Who is new? Are there grade inconsistencies? Any patterns in performance distribution? This is input to your team assessment.',
    phase: 1,
    default_week: 1,
    category: 'People',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'group-learning',
    depth: 1,
  },

  // Section B: Big Picture Learning Topics
  {
    id: 'learn-past-performance',
    title: 'Past performance',
    description: 'Understand how the team and organisation has performed historically.',
    detail: 'How has the team/organisation performed historically? How were goals set — top-down or collaboratively? What benchmarks were used? What incentives existed and what behaviours did they encourage? What are the root causes of any underperformance? What\'s the history of change initiatives and which succeeded or failed, and why? Understanding the past is essential context for diagnosing the present.',
    phase: 1,
    default_week: 2,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'learn-vision-strategy',
    title: 'Vision and strategy',
    description: 'Understand the stated vision and strategy — and whether the organisation is really pursuing it.',
    detail: 'What is the stated vision and strategy — for the organisation and for your team specifically? Is the organisation really pursuing it, or is there a gap between rhetoric and reality? If there\'s a gap, why? What are the future opportunities and challenges for your team? What are the major barriers to delivering the strategy? What resources would be needed? This is the most important thing to get clarity on before you develop your own view.',
    phase: 1,
    default_week: 2,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'learn-people',
    title: 'People',
    description: 'Build a mental model of who is capable, trustworthy, and influential.',
    detail: 'Who in your team and across the organisation is capable, trustworthy, and influential? These three qualities are distinct: someone can be highly capable but politically marginal; someone can be influential but not trustworthy. Build a mental model of the human landscape — who gets things done, who blocks things, who knows where the bodies are buried, who is a genuine ally. The People tab in this app is the place to capture this.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'learn-processes',
    title: 'Processes',
    description: 'Understand what the key processes are and whether they\'re performing.',
    detail: 'What are the key processes in your team and the wider organisation? Are they performing — i.e., do they reliably produce the outcomes they\'re supposed to? Where are the bottlenecks, the workarounds, the processes that exist on paper but not in practice? Good process insight is often the fastest route to early wins.',
    phase: 1,
    default_week: 2,
    category: 'Process',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'learn-landmines',
    title: 'Land mines',
    description: 'Identify the surprises, risks, and potential cultural missteps you need to know about.',
    detail: 'What are the surprises, risks, and potential cultural missteps you need to know about? Look across four domains: (1) External environment — what\'s changing in the market, regulation, or sector that could catch you out? (2) Customers/stakeholders — who is unhappy, what commitments have been made? (3) Internal capability — where are the fragilities in the team or processes? (4) Internal politics — what historical tensions, rivalries, or sensitivities exist? Ask people explicitly: "What do I need to know that I don\'t know yet?"',
    phase: 1,
    default_week: 2,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'learn-culture',
    title: 'Culture',
    description: 'Understand the culture you\'ll be swimming in before you try to change it.',
    detail: 'Culture is felt before it is understood. Pay attention to: logos, dress, and physical environment (what does the space say about priorities?); language and acronyms (every org has its own dialect); the balance between delivery focus and people focus; the norms around hierarchy, dissent, and recognition; and the shared assumptions — the things everyone "knows" that are never written down. Culture is the water you\'ll swim in. Understand it before you try to change it.',
    phase: 1,
    default_week: 2,
    category: 'Self',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },

  // Section C: Listening Tour
  {
    id: 'listening-tour-boss',
    title: 'Listening tour — Line Manager',
    description: 'Use a consistent question set to structure your early conversations with your boss.',
    detail: 'Use a consistent question set to structure your early conversations. Good questions: What are the biggest challenges facing the team? Why are we facing these challenges? What are the most promising opportunities? What would you need to exploit them? If you were in my position, what would you focus on? Test what you hear for alignment with the top-down strategy. Listen for what\'s said and what\'s carefully not said.',
    phase: 1,
    default_week: 2,
    category: 'Relationships',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Negotiate Success'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'listening-tour-direct-reports',
    title: 'Listening tour — Direct reports',
    description: 'Meet each direct report 1:1 early — listen before you signal your own views.',
    detail: 'Meet each direct report 1:1 early. Use a consistent structure: understand their role, their view of team performance and priorities, what they think is working and not working, and what support they want from you. Resist the urge to signal your own views — you\'re in listening mode. What people tell you in these early conversations (before they know how you operate) is often your most honest data.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'critical',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'listening-tour-dr-prepare-questions',
    title: 'Prepare listening tour questions',
    description: 'Draft a consistent question set to use across all direct report 1:1s.',
    detail: 'Write out 8–12 open questions you will ask every direct report. Include: What are the biggest challenges? What is working well? What would you change if you could? What do you need from me? Consistency lets you compare across conversations and spot patterns.',
    phase: 1,
    default_week: 1,
    category: 'People',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'listening-tour-direct-reports',
    depth: 2,
  },
  {
    id: 'listening-tour-dr-schedule-1on1s',
    title: 'Schedule all direct report 1:1s',
    description: 'Get every direct report 1:1 in the calendar within the first two weeks.',
    detail: 'Block 45–60 minutes per person. Aim for a quiet space (not a glass fishbowl). Space them out so you have time to reflect between conversations. Send a brief note saying what to expect: "I want to learn about you and your work — no agenda, just a conversation."',
    phase: 1,
    default_week: 1,
    category: 'People',
    priority: 'critical',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'listening-tour-direct-reports',
    depth: 2,
  },
  {
    id: 'listening-tour-dr-synthesise',
    title: 'Synthesise listening tour findings',
    description: 'After all direct report conversations, synthesise themes and patterns.',
    detail: 'Review your notes across all conversations. Identify: (1) points of consensus — what everyone agrees on; (2) points of divergence — where views differ; (3) unspoken themes — what was carefully avoided. Write a one-page summary. This becomes a key input to your diagnosis.',
    phase: 1,
    default_week: 4,
    category: 'People',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'listening-tour-direct-reports',
    depth: 2,
  },
  {
    id: 'listening-tour-wider-team',
    title: 'Listening tour — Wider team',
    description: 'Connect with the broader team beyond direct reports for ground-level insights.',
    detail: 'Beyond direct reports, find ways to connect with the broader team. Skip-level conversations (where appropriate), team meetings, informal coffees. You\'re building a ground-level view of culture, morale, and operational reality that your direct reports may not share with you directly.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'listening-tour-peers',
    title: 'Listening tour — Peers',
    description: 'Invest early in understanding peer leaders — they control resources and informal influence.',
    detail: 'Your peers — other directors, heads of department, or equivalent — are critical to your success. They control resources, information, and informal influence. Invest early in understanding their priorities, their view of your team, and what they need from you. Don\'t wait for them to come to you.',
    phase: 1,
    default_week: 2,
    category: 'Relationships',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Create Alliances'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'listening-tour-enablers',
    title: 'Listening tour — Key business enablers',
    description: 'Build relationships with enabling functions before you need something from them.',
    detail: 'Identify the people outside your direct team who enable your team to function — finance partners, HR, IT, legal, communications, central strategy. Build relationships before you need something. Understand their constraints and priorities. These relationships will determine how quickly you can get things done.',
    phase: 1,
    default_week: 2,
    category: 'Relationships',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Create Alliances'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'listening-tour-external',
    title: 'Listening tour — External stakeholders',
    description: 'Meet key external stakeholders for an unfiltered outside-in view.',
    detail: 'Clients, suppliers, partners, funders, regulators, sector peers. External relationships often reveal what internal conversations won\'t. External stakeholders will give you an unfiltered view of the organisation\'s reputation, delivery quality, and strategic positioning. Prioritise by influence and relationship risk.',
    phase: 1,
    default_week: 5,
    category: 'Relationships',
    priority: 'high',
    start_week: 3,
    end_week: 7,
    watkins_groups: ['Accelerate Your Learning', 'Create Alliances'],
    parent_id: 'group-learning',
    depth: 1,
  },

  // Section D: Advanced Learning Methods
  {
    id: 'diagnostic-methods',
    title: 'Consider using additional diagnostic methods',
    description: 'Add structure and rigour to your diagnosis with targeted methods.',
    detail: 'By weeks 3–5, you\'ll have enough qualitative data to know where your blind spots are. Consider where structured diagnostic methods would add rigour. Don\'t use them as a substitute for direct conversation — use them to triangulate and deepen your understanding of specific areas.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'diagnostic-consultants',
    title: 'Diagnostic methods — Consultants',
    description: 'Bring in external expertise for specific diagnostic questions.',
    detail: 'Consider bringing in consultants for specific areas where external expertise or independence would add value. Define the question first, then identify whether external resource is truly needed.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'diagnostic-methods',
    depth: 1,
  },
  {
    id: 'diagnostic-surveys',
    title: 'Diagnostic methods — Surveys',
    description: 'Use structured data collection to surface themes across team or stakeholders.',
    detail: 'Surveys provide structured data at scale. Useful for gauging team sentiment, stakeholder perceptions, or testing hypotheses you\'ve formed from conversations. Keep surveys short and act on what you learn.',
    phase: 1,
    default_week: 4,
    category: 'Process',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'diagnostic-methods',
    depth: 1,
  },
  {
    id: 'diagnostic-focus-groups',
    title: 'Diagnostic methods — Focus Groups',
    description: 'Use facilitated discussion to surface themes.',
    detail: 'Facilitated focus groups can surface collective views and surface themes that individual conversations don\'t reveal. Useful for understanding team culture, morale, or response to potential changes.',
    phase: 1,
    default_week: 4,
    category: 'People',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'diagnostic-methods',
    depth: 1,
  },
  {
    id: 'diagnostic-process-analysis',
    title: 'Diagnostic methods — Process analysis',
    description: 'Map a key process end-to-end to identify failure points.',
    detail: 'Select one or two key processes and map them end-to-end. Where are the handoff failures? Where are the bottlenecks? Where does the process differ from what\'s written down? Process analysis often reveals structural problems that conversations alone won\'t surface.',
    phase: 1,
    default_week: 4,
    category: 'Process',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'diagnostic-methods',
    depth: 1,
  },
  {
    id: 'diagnostic-issue-deep-dives',
    title: 'Diagnostic methods — Issue deep dives',
    description: 'Take one specific problem and investigate it thoroughly.',
    detail: 'Pick one significant problem you\'ve identified and investigate it thoroughly — talk to everyone involved, review the data, trace it back to root causes. Deep dives on individual issues often reveal systemic patterns that apply across the organisation.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'diagnostic-methods',
    depth: 1,
  },

  // Section E: Diagnose
  {
    id: 'swot-analysis',
    title: 'Build a SWOT analysis',
    description: 'Synthesise your diagnostic findings into a coherent SWOT picture.',
    detail: 'Use the SWOT framework (Strengths, Weaknesses, Opportunities, Threats) to structure your diagnostic findings into a coherent picture. The SWOT should draw on everything you\'ve learned — financial performance, people, processes, culture, external environment. It\'s not an exercise in itself; it\'s a synthesis tool. Revisit and update it as your understanding develops.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'swot-gather-strengths',
    title: 'Gather strength evidence',
    description: 'Collect concrete evidence of what the team and organisation does well.',
    detail: 'Draw on financial data, stakeholder feedback, listening tour themes, and your own observations. List specific capabilities, assets, relationships, and cultural strengths. Be evidence-based — "strong team culture" is too vague; "low voluntary turnover, high engagement scores, multiple people cited pride in the work" is better.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'high',
    start_week: 2,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'swot-analysis',
    depth: 2,
  },
  {
    id: 'swot-identify-weaknesses',
    title: 'Identify key weaknesses',
    description: 'Honestly catalogue internal weaknesses — capability gaps, process failures, cultural blockers.',
    detail: 'Look for: skill gaps, underperforming processes, cultural norms that hinder delivery, structural misalignments, resource constraints, and leadership gaps. Cross-reference what people told you in listening tours with what the data shows. Where conversations and data align, the signal is strong.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'high',
    start_week: 2,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'swot-analysis',
    depth: 2,
  },
  {
    id: 'swot-map-opportunities',
    title: 'Map opportunities',
    description: 'Identify external opportunities the team could capitalise on.',
    detail: 'Look at market trends, policy changes, new funding streams, technology shifts, unmet stakeholder needs, and partnership possibilities. For each opportunity, assess: How significant is it? How time-sensitive? Do we have the capability to exploit it? What would we need to invest?',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'swot-analysis',
    depth: 2,
  },
  {
    id: 'swot-assess-threats',
    title: 'Assess threats',
    description: 'Identify external threats and risks that could undermine the team\'s success.',
    detail: 'Consider: competitive pressures, regulatory changes, funding risks, talent market shifts, technology disruption, reputational risks, and macro-economic factors. For each threat, assess likelihood and impact. Distinguish between threats you can mitigate and those you can only monitor.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'swot-analysis',
    depth: 2,
  },
  {
    id: 'porters-five-forces',
    title: 'Consider Porter\'s Five Forces',
    description: 'Apply Five Forces analysis if your role has external or strategic dimensions.',
    detail: 'Particularly relevant if your role has external/strategic dimensions. The Five Forces (competitive rivalry, threat of new entrants, threat of substitutes, bargaining power of buyers, bargaining power of suppliers) give a structured lens on the competitive environment. For a public sector or non-profit role, adapt the framework to your context — funders, government policy, sector dynamics.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'normal',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'stars-assessment',
    title: 'Assess the STARS situation',
    description: 'Apply Watkins\' STARS model to your situation and key business units.',
    detail: 'Apply Watkins\' STARS model to your situation and to individual products, projects, or business units you\'re responsible for. Classify each as: Start-up (building from scratch), Turnaround (fixing a serious problem), Accelerated growth (scaling what works), Realignment (refocusing away from complacency), or Sustaining success (maintaining high performance). Different STARS situations require different leadership approaches. Getting this diagnosis wrong leads to applying the wrong playbook.',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 6,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'form-hypotheses',
    title: 'Form hypotheses about the business',
    description: 'Start making explicit hypotheses — test and update them as you learn.',
    detail: 'Don\'t wait until you have complete information — that never comes. From week 2 onwards, start forming explicit hypotheses about what\'s driving performance, what\'s broken, and what needs to change. Write them down. Test them in conversations. Update them as you learn. The discipline of explicit hypothesis formation stops you from gathering data indefinitely and never committing to a view.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 6,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'develop-strategy-options',
    title: 'Develop a strategy — with options',
    description: 'Once diagnosis is solid, develop strategic options rather than a single plan.',
    detail: 'Once your diagnosis is solid (weeks 5–6), you\'re ready to develop strategic options. Consider: What STARS situations do you face? What are the challenges and opportunities? What does the learning agenda imply about priorities? What is the prevailing mood and what change is the organisation capable of absorbing? What are your own strengths and what does that imply for team composition? Present options rather than a single plan — this shows rigour and creates space for consultation. Remember: mission = what you want to achieve; vision = why (the motivator); strategy = how.',
    phase: 2,
    default_week: 8,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Accelerate Your Learning', 'Achieve Alignment'],
    parent_id: 'group-learning',
    depth: 1,
  },
  {
    id: 'think-early-wins-learning',
    title: 'Think about early wins throughout the learning phase',
    description: 'Keep a running list of potential early wins as you observe — don\'t act yet.',
    detail: 'Even as you\'re in learning mode, keep a running list of potential early wins you observe. An early win is something that: (a) addresses a genuine problem, (b) is achievable within your current authority and resources, (c) demonstrates your values and priorities, and (d) builds momentum and credibility. You\'re not acting on these yet — just noticing them.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 7,
    watkins_groups: ['Accelerate Your Learning', 'Secure Early Wins'],
    parent_id: 'group-learning',
    depth: 1,
  },

  // Section F: Consult and Share
  {
    id: 'share-preliminary-diagnosis',
    title: 'Share preliminary diagnosis with team',
    description: 'Test your assumptions and build trust by sharing what you\'ve found.',
    detail: 'Before finalising your diagnosis, share a preliminary version with your direct reports. This serves multiple purposes: it tests your assumptions, it demonstrates that you listened, it builds trust, and it invites ownership. Frame it as "here\'s what I\'m hearing — does this resonate? What am I missing?" Not "here\'s what I\'ve decided." The conversation often reveals things no individual told you directly.',
    phase: 2,
    default_week: 5,
    category: 'People',
    priority: 'high',
    start_week: 5,
    end_week: 6,
    watkins_groups: ['Accelerate Your Learning', 'Negotiate Success'],
    parent_id: 'group-learning',
    depth: 1,
  },


  // ─── GROUP 3: NEGOTIATING SUCCESS ────────────────────────────────────────

  {
    id: 'group-negotiate',
    title: 'Negotiate Success',
    description: 'The conversations with your boss and direct reports that determine whether you succeed or struggle.',
    detail: 'These aren\'t one-offs — they\'re recurring touchpoints that evolve as your tenure progresses. Getting these conversations right is one of the highest-leverage activities in your first 90 days.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Negotiate Success'],
    depth: 0,
  },
  {
    id: 'relationship-boss',
    title: 'Relationship building — Boss',
    description: 'Build a genuine human connection with your boss before the professional relationship takes over.',
    detail: 'Your first 1:1 with your boss should be about them, not you. Ask about their career, what they care about, how they work, what they\'ve learned. This builds a genuine human connection before the professional relationship takes over. People support leaders they like and trust — start building that foundation immediately.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 1,
    end_week: 1,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'relationship-direct-reports',
    title: 'Relationship building — Direct reports',
    description: 'Invest in getting to know each direct report as an individual before making any assessments.',
    detail: 'Same intent with your direct reports. Invest in getting to know each person as an individual before you make any assessments or decisions about them. Ask about their background, what they\'re proud of, what frustrates them, what they\'re hoping for from a new leader. This creates psychological safety that pays dividends throughout your tenure.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 1,
    end_week: 1,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'style-boss',
    title: 'Style conversation — Boss',
    description: 'Explicitly discuss working style with your boss early to prevent friction.',
    detail: 'Explicitly discuss working style with your boss early. Key questions: What decisions do you want to be consulted on vs. informed after the fact? How often do you want 1:1s and what format works for you? Do you prefer email, instant messaging, or in-person for different types of communication? How do you like to receive bad news? Getting this right prevents a lot of friction.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'style-direct-reports',
    title: 'Style conversation — Direct reports',
    description: 'Discuss working style with each direct report and set your own expectations.',
    detail: 'Have the same conversation with each direct report — but this time you\'re also setting your own expectations. Be clear about: how you\'ll operate, what you expect from them, how you want to be kept informed, your preferences on decision-making authority. Be explicit rather than assuming people will figure it out.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'expectations-boss-w1',
    title: 'Expectations — Boss (Week 1 check-in)',
    description: 'Establish a shared baseline of expectations in your first week.',
    detail: 'In your first week, have an explicit conversation about initial expectations. What does success look like in the first 30 days? What are the immediate priorities you should focus on? What would be a red flag in your first month? Are there any existing commitments or promises made to stakeholders that you need to know about? Establishing a shared baseline of expectations early prevents misalignment building silently.',
    phase: 1,
    default_week: 1,
    category: 'Relationships',
    priority: 'critical',
    start_week: 1,
    end_week: 1,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'expectations-boss-w5',
    title: 'Expectations — Boss (Week 5 check-in)',
    description: 'Revisit expectations at the five-week mark with your developing diagnosis.',
    detail: 'At the five-week mark, revisit expectations with more substance. Share your developing diagnosis and get your boss\'s reaction. Discuss your plan for the next month — what you intend to focus on, what you want to achieve, what you need from them. Check alignment: are your priorities matching theirs? Use this as a two-way expectation-setting conversation, not just an update.',
    phase: 2,
    default_week: 5,
    category: 'Relationships',
    priority: 'critical',
    start_week: 5,
    end_week: 5,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'expectations-boss-w9',
    title: 'Expectations — Boss (Week 9 check-in)',
    description: 'Have the longer-term expectations conversation at the two-month mark.',
    detail: 'At week 9 — roughly two months in — have the longer-term expectations conversation. What does success look like by end of probation? By end of year? What development or resource support would help you get there? Are there areas where your boss has concerns? This is the conversation where you begin to establish your longer-term standing in the organisation.',
    phase: 3,
    default_week: 9,
    category: 'Relationships',
    priority: 'critical',
    start_week: 9,
    end_week: 9,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'expectations-direct-reports',
    title: 'Expectations — Direct reports',
    description: 'Set clear expectations with each direct report early — then revisit them.',
    detail: 'Set clear expectations with each direct report early — then revisit them. Be explicit about: performance standards, how you\'ll assess contribution, your values, what you will and won\'t tolerate. Don\'t assume inherited expectations are right — you may need to reset them. Revisit at the month mark to check alignment.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'situation-boss',
    title: 'Situation conversation — Boss',
    description: 'Get your boss\'s framing of the political and organisational landscape.',
    detail: 'Have a focused conversation with your boss about the situational context: What is the political and organisational landscape? Who are the key informal power players? What are the sensitivities? What is the history behind current challenges? Your boss\'s framing of the situation is important data — note where it aligns with and diverges from what you\'re hearing from others.',
    phase: 1,
    default_week: 2,
    category: 'Relationships',
    priority: 'high',
    start_week: 2,
    end_week: 6,
    watkins_groups: ['Negotiate Success', 'Match Strategy to Situation'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'situation-direct-reports',
    title: 'Situation conversation — Direct reports',
    description: 'Get each direct report\'s view of the situation and compare across the team.',
    detail: 'Get each direct report\'s view of the situation: What are the biggest problems? Where is the team strong and where does it struggle? What\'s their read on the organisational dynamics? Compare across reports — where there\'s consensus, the signal is strong. Where views diverge, dig deeper.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'high',
    start_week: 2,
    end_week: 6,
    watkins_groups: ['Negotiate Success', 'Accelerate Your Learning'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'diagnosis-strategy-boss',
    title: 'Diagnosis and strategy conversation — Boss',
    description: 'Test your preliminary diagnosis with your boss, then co-develop strategy.',
    detail: 'Once you have a preliminary diagnosis (weeks 5–6), present it to your boss. Frame it as "here\'s my current read — I want to test this with you." Then, as strategy develops, bring options and seek input before committing. Present diagnosis first, then strategy — don\'t jump to solutions before you\'ve aligned on the problem. Your boss needs to be a co-author of the strategy, not an audience for it.',
    phase: 2,
    default_week: 5,
    category: 'Relationships',
    priority: 'critical',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Negotiate Success', 'Achieve Alignment'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'diagnosis-strategy-direct-reports',
    title: 'Diagnosis and strategy conversation — Direct reports',
    description: 'Share your diagnosis and consult direct reports before finalising strategy.',
    detail: 'Share your diagnosis with direct reports — both individually and collectively. Consider a team session to share your overall read and invite challenge. When strategy develops, consult with reports before finalising. People implement strategies they helped shape with far more energy than strategies handed down to them.',
    phase: 2,
    default_week: 5,
    category: 'People',
    priority: 'high',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'resourcing-boss',
    title: 'Resourcing conversation — Boss',
    description: 'Make the resource conversation explicit — link requests to strategic options.',
    detail: 'Once you have a clear strategy and an understanding of the gap between current capability and what\'s needed, make the resource conversation explicit. Link resource requests to strategic options — "to deliver X, we need Y." This is more compelling than a headcount bid in isolation. Aim to have this conversation fully resolved before the end of your first quarter.',
    phase: 3,
    default_week: 12,
    category: 'Relationships',
    priority: 'high',
    start_week: 9,
    end_week: 13,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'resourcing-direct-reports',
    title: 'Resourcing conversation — Direct reports',
    description: 'Understand what resource constraints your direct reports are operating under.',
    detail: 'Understand the resource constraints and pressures your direct reports are operating under. What is blocking their ability to perform? What do they need that they\'re not getting? Use this to inform your resourcing conversation with your boss and to demonstrate that you understand the operational reality.',
    phase: 3,
    default_week: 11,
    category: 'People',
    priority: 'high',
    start_week: 2,
    end_week: 13,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'development-boss',
    title: 'Development conversation — Boss',
    description: 'Ask for feedback on your own development — early and at the end of the quarter.',
    detail: 'Early on (weeks 4–5), have a brief check-in with your boss on your own development — how are you doing, are there areas to focus on, is there feedback you should hear now rather than later? At weeks 12–13, have a fuller development conversation: what are your strengths in this role, where do you need to grow, what support would help? Don\'t wait for your boss to initiate this.',
    phase: 3,
    default_week: 12,
    category: 'Self',
    priority: 'high',
    start_week: 4,
    end_week: 13,
    watkins_groups: ['Negotiate Success', 'Manage Yourself'],
    parent_id: 'group-negotiate',
    depth: 1,
  },
  {
    id: 'development-direct-reports',
    title: 'Development conversation — Direct reports',
    description: 'Establish a regular development conversation cadence with each direct report.',
    detail: 'After the first month, establish a regular development/career conversation cadence with each direct report — ideally monthly. By week 6–7 you should have enough of a relationship and enough data to have a meaningful conversation. Ask: What are your ambitions? What do you want to develop? What can I do to support you? These conversations build loyalty and retention.',
    phase: 2,
    default_week: 6,
    category: 'People',
    priority: 'high',
    start_week: 6,
    end_week: 13,
    watkins_groups: ['Negotiate Success', 'Build Your Team'],
    parent_id: 'group-negotiate',
    depth: 1,
  },


  // ─── GROUP 4: SECURE EARLY WINS ──────────────────────────────────────────

  {
    id: 'group-early-wins',
    title: 'Secure Early Wins',
    description: 'Early wins are about credibility, momentum, and signal — not just results.',
    detail: 'Think in waves: learning phase (weeks 1–10), early small changes (weeks 10–17), consolidation (weeks 17–26), deeper changes (weeks 26–39), fine-tuning thereafter.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 7,
    watkins_groups: ['Secure Early Wins'],
    depth: 0,
  },
  {
    id: 'identify-issues-diagnosis',
    title: 'Identify issues through diagnosis',
    description: 'Actively look for the common organisational problems that early wins typically address.',
    detail: 'As you learn, actively look for the common organisational problems that early wins typically address. Possible issues to look for: (1) Focus — unclear or too many priorities, resources spread too thin; (2) Discipline — failure to meet commitments, low or variable performance; (3) Innovation — slow to innovate, rewarding stable over progressive performance, wrong benchmarks; (4) Teamwork — poor collaboration, fiefdoms, internal competition; (5) Urgency — complacency, lack of drive. Identify which of these are present and which are most tractable.',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 5,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'group-early-wins',
    depth: 1,
  },
  {
    id: 'shortlist-projects',
    title: 'Shortlist possible projects',
    description: 'From your issues list, identify a shortlist of potential early win projects.',
    detail: 'From your issues list, identify a shortlist of potential early win projects. Criteria for a good early win: (a) genuinely addresses an important problem, (b) is achievable within current authority and resources, (c) can be completed and seen to be completed within ~60 days, (d) involves and benefits your team (not just a solo achievement), (e) aligns with the strategic direction you\'re developing. Avoid quick wins that are superficial or damage relationships.',
    phase: 1,
    default_week: 5,
    category: 'Strategy',
    priority: 'high',
    start_week: 2,
    end_week: 7,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'group-early-wins',
    depth: 1,
  },
  {
    id: 'assess-early-win-projects',
    title: 'Assess potential early win projects',
    description: 'Rigorously assess each shortlisted project before committing.',
    detail: 'For each shortlisted project, assess: What\'s the realistic impact? What resources would it require? Who do I need on side to make it happen? What are the risks — could this go wrong and damage credibility rather than build it? What does success look like and how will it be visible? The discipline of assessment stops you launching into something that feels like a win but isn\'t.',
    phase: 2,
    default_week: 6,
    category: 'Strategy',
    priority: 'high',
    start_week: 5,
    end_week: 7,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'group-early-wins',
    depth: 1,
  },
  {
    id: 'pitch-early-wins-boss',
    title: 'Pitch early win ideas to your boss',
    description: 'Sanity-check early win ideas with your boss before committing resources.',
    detail: 'Before committing resources to an early win project, sanity-check it with your boss. Frame it as: "I\'ve identified [problem], I think [initiative] could address it, here\'s what I\'d need — does this make sense to you?" You want boss alignment before you engage the team. This also surfaces any political sensitivities or history you may not be aware of.',
    phase: 2,
    default_week: 6,
    category: 'Relationships',
    priority: 'high',
    start_week: 5,
    end_week: 7,
    watkins_groups: ['Secure Early Wins', 'Negotiate Success'],
    parent_id: 'group-early-wins',
    depth: 1,
  },

  // ─── GROUP 5: ACHIEVE ALIGNMENT / STRATEGY DEVELOPMENT ───────────────────

  {
    id: 'group-alignment',
    title: 'Achieve Alignment / Strategy Development',
    description: 'Broad process: diagnose → consult → develop options → consult → set strategy → roadmap → align organisation.',
    detail: 'This runs from week 5 through to end of quarter. The goal is a coherent strategy with organisational alignment across structure, processes, capability, and culture.',
    phase: 2,
    default_week: 6,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Achieve Alignment', 'Match Strategy to Situation'],
    depth: 0,
  },
  {
    id: 'complete-full-diagnosis',
    title: 'Complete full diagnosis',
    description: 'Bring together everything you\'ve learned into a coherent diagnostic picture.',
    detail: 'By weeks 5–6, bring together everything you\'ve learned into a coherent diagnostic picture. This is the synthesis of your SWOT, STARS assessment, hypotheses, listening tour findings, and financial/performance data. Write it down — not for publication, but to force clarity. The act of writing exposes gaps in your understanding. Your diagnosis is the foundation for everything that follows.',
    phase: 2,
    default_week: 5,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 6,
    watkins_groups: ['Achieve Alignment', 'Accelerate Your Learning'],
    parent_id: 'group-alignment',
    depth: 1,
  },
  {
    id: 'develop-strategy-options-alignment',
    title: 'Develop strategy options',
    description: 'Develop 2–3 strategic options with mission, vision, strategy, and trade-offs.',
    detail: 'Develop 2–3 strategic options rather than a single plan. For each option, articulate: the mission (what you\'re trying to achieve), the vision (why — the motivating purpose), the strategy (how you\'ll get there), and the key trade-offs. Options allow you to consult more genuinely — you\'re not asking people to sign off on a decision already made; you\'re asking for input on a real choice.',
    phase: 2,
    default_week: 8,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 10,
    watkins_groups: ['Achieve Alignment', 'Match Strategy to Situation'],
    parent_id: 'group-alignment',
    depth: 1,
  },
  {
    id: 'review-alignment-dimensions',
    title: 'Review alignment of strategy, structure, processes, and capability',
    description: 'Test whether the organisation is aligned to deliver your strategic direction.',
    detail: 'Once you have a strategic direction, test whether the organisation is aligned to deliver it. Check four dimensions: (1) Structure — does the reporting structure support the strategy? Are the right teams grouped together? (2) Processes — do the operating processes (meetings, decision rights, reporting) enable or obstruct delivery? (3) Capability — do individuals have the skills needed? Are there gaps? (4) Culture — do the values and norms reinforce or undermine the strategy? Misalignment in any of these dimensions will constrain delivery even if the strategy is right.',
    phase: 2,
    default_week: 10,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 11,
    watkins_groups: ['Achieve Alignment', 'Match Strategy to Situation'],
    parent_id: 'group-alignment',
    depth: 1,
  },
  {
    id: 'build-roadmap',
    title: 'Build a roadmap',
    description: 'Translate the strategy into a concrete 12-month roadmap.',
    detail: 'Translate the strategy into a 12-month roadmap: key milestones, sequencing of changes, resource requirements, decision points, and review cadence. The roadmap is the commitment device — it turns strategy from intent into plan. It should be concrete enough to be held accountable to but flexible enough to adapt as context changes. Share it with your boss and team before the end of your first quarter.',
    phase: 3,
    default_week: 12,
    category: 'Strategy',
    priority: 'critical',
    start_week: 11,
    end_week: 13,
    watkins_groups: ['Achieve Alignment'],
    parent_id: 'group-alignment',
    depth: 1,
  },

  // ─── GROUP 6: BUILD YOUR TEAM ─────────────────────────────────────────────

  {
    id: 'group-team',
    title: 'Build Your Team',
    description: 'Team-building runs the entire 90 days — from assessment to structural decisions and cultural development.',
    detail: 'Starts with assessment and relationship-building, and progresses to structural decisions and cultural alignment. The team you build will ultimately determine what you can achieve.',
    phase: 1,
    default_week: 2,
    category: 'People',
    priority: 'critical',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Build Your Team'],
    depth: 0,
  },
  {
    id: 'assess-team',
    title: 'Assess the team',
    description: 'Build a structured assessment of each team member using consistent criteria.',
    detail: 'Build a structured assessment of each team member using consistent criteria: competence (can they do the job?), judgment (do they make good decisions?), energy (do they bring drive and commitment?), focus (are they working on the right things?), relationships (do they work well with others?), trust (are they reliable and honest?). Rate each out of 10, weight the criteria by what matters most in your context, and set minimum thresholds for adequacy. For each person, reach a provisional conclusion: keep as-is / keep and develop / move to different role / replace (high or low urgency) / observe further. Be honest with yourself — wishful thinking about team members is a common failure mode.',
    phase: 1,
    default_week: 4,
    category: 'People',
    priority: 'critical',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Build Your Team'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'assess-team-profiles',
    title: 'Create individual assessment profiles',
    description: 'Build a structured profile for each team member using the six criteria.',
    detail: 'For each direct report, create a profile scoring competence, judgment, energy, focus, relationships, and trust. Document the evidence behind each score — not just a gut feel. Include specific examples from meetings, observations, and feedback from others. This is your working document, not for sharing.',
    phase: 1,
    default_week: 4,
    category: 'People',
    priority: 'high',
    start_week: 3,
    end_week: 8,
    watkins_groups: ['Build Your Team'],
    parent_id: 'assess-team',
    depth: 2,
  },
  {
    id: 'assess-team-competence-alignment',
    title: 'Map competence vs alignment',
    description: 'Plot each team member on a competence vs alignment matrix.',
    detail: 'Create a 2x2 matrix: competence (can they do the job?) on one axis, alignment (are they pulling in the right direction?) on the other. High competence + high alignment = your core. High competence + low alignment = a coaching challenge. Low competence + high alignment = a development opportunity. Low on both = the hardest conversation. This framing helps you prioritise where to invest your time.',
    phase: 1,
    default_week: 5,
    category: 'People',
    priority: 'high',
    start_week: 4,
    end_week: 9,
    watkins_groups: ['Build Your Team'],
    parent_id: 'assess-team',
    depth: 2,
  },
  {
    id: 'assess-team-high-performers',
    title: 'Identify high performers needing investment',
    description: 'Identify your best people and plan how to retain and develop them.',
    detail: 'Your highest performers are your most at-risk people — they have options. Identify who they are and what they need: recognition, development, stretch assignments, autonomy, or support. Have an early conversation with each one about their aspirations. Losing a top performer in your first quarter is a significant setback.',
    phase: 2,
    default_week: 6,
    category: 'People',
    priority: 'high',
    start_week: 5,
    end_week: 10,
    watkins_groups: ['Build Your Team'],
    parent_id: 'assess-team',
    depth: 2,
  },
  {
    id: 'early-personnel-decisions',
    title: 'Consider early personnel decisions',
    description: 'Face serious performance or fit issues honestly — delay rarely helps.',
    detail: 'If your assessment reveals serious performance or fit issues, face them honestly. Personnel decisions are rarely improved by delay — the longer you wait, the more you\'re implicitly endorsing the status quo. Early decisions also send a signal about your standards. However, be careful: don\'t make personnel decisions before you understand the full context, and always act with fairness and due process. If in doubt about someone, observe further rather than act prematurely.',
    phase: 2,
    default_week: 10,
    category: 'People',
    priority: 'high',
    start_week: 8,
    end_week: 13,
    watkins_groups: ['Build Your Team'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'long-term-personnel-decisions',
    title: 'Long-term personnel decisions',
    description: 'Identify decisions that need to wait — and prepare the groundwork now.',
    detail: 'Some personnel decisions — particularly those involving senior hires, restructuring, or exits — will need to wait until you have full authority, budget clarity, and a finalised strategy. Use your first quarter to identify these decisions, understand the constraints, and prepare the groundwork so you\'re ready to act in quarter 2.',
    phase: 3,
    default_week: 13,
    category: 'People',
    priority: 'normal',
    start_week: 13,
    end_week: 13,
    watkins_groups: ['Build Your Team'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'review-team-meetings',
    title: 'Review team meetings — use, format, and frequency',
    description: 'Observe existing team meetings before changing them.',
    detail: 'Early on, attend existing team meetings as an observer before changing them. By weeks 4–6, form a view: are the right people in the room? Is the right content being discussed? Is the format working? Are meetings too frequent, too infrequent, or the wrong type? Make changes thoughtfully — meetings are highly visible cultural signals.',
    phase: 1,
    default_week: 5,
    category: 'Process',
    priority: 'high',
    start_week: 4,
    end_week: 6,
    watkins_groups: ['Build Your Team', 'Accelerate Everyone'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'establish-1on1s',
    title: 'Establish 1:1s with each direct report',
    description: 'Set up a regular 1:1 cadence with each direct report by week 3.',
    detail: 'Set up a regular 1:1 cadence with each direct report by week 3. Agree format, frequency, and agenda structure. The 1:1 is the primary vehicle for performance management, development, and relationship-building. Don\'t let this become an ad hoc catch-up — give it structure and protect the time.',
    phase: 1,
    default_week: 3,
    category: 'People',
    priority: 'critical',
    start_week: 3,
    end_week: 3,
    watkins_groups: ['Build Your Team', 'Negotiate Success'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'check-support-roles',
    title: 'Check you have the right support roles in the team',
    description: 'Identify gaps in administrative, analytical, or specialist support.',
    detail: 'Are there gaps in administrative, analytical, or specialist support that are constraining the team? Is the EA/PA function working? Are there support roles that are duplicated or redundant? This is often a quick win — the right support infrastructure pays back quickly.',
    phase: 1,
    default_week: 5,
    category: 'Process',
    priority: 'high',
    start_week: 4,
    end_week: 6,
    watkins_groups: ['Build Your Team', 'Accelerate Everyone'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'create-development-checkins',
    title: 'Create career and development check-ins',
    description: 'Establish a regular development conversation cadence with each direct report.',
    detail: 'By week 6, establish a regular development conversation cadence with each direct report. These are distinct from performance 1:1s — they\'re forward-looking, career-focused conversations. Monthly is ideal. The signal you send by investing in people\'s development early is powerful.',
    phase: 2,
    default_week: 6,
    category: 'People',
    priority: 'high',
    start_week: 6,
    end_week: 6,
    watkins_groups: ['Build Your Team', 'Accelerate Everyone'],
    parent_id: 'group-team',
    depth: 1,
  },
  {
    id: 'align-team-strategy',
    title: 'Align team with strategy through communication and objectives',
    description: 'Bring the team along as your strategy crystallises.',
    detail: 'As your strategy crystallises, bring the team along. Sequence: (1) share your diagnosis first — explain what you\'ve found and get reaction; (2) consult on strategic options with key people; (3) share the finalised strategy and the reasoning behind it; (4) translate the strategy into team objectives (not just individual tasks); (5) align incentives and recognition with strategic priorities. Done well, this transforms your team from people executing tasks to people pursuing a shared mission.',
    phase: 2,
    default_week: 8,
    category: 'People',
    priority: 'critical',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Build Your Team', 'Achieve Alignment'],
    parent_id: 'group-team',
    depth: 1,
  },

  // ─── GROUP 7: CREATE ALLIANCES ────────────────────────────────────────────

  {
    id: 'group-alliances',
    title: 'Create Alliances',
    description: 'Senior leadership success depends heavily on lateral influence.',
    detail: 'Your ability to get things done through people you don\'t manage is as important as your formal authority. Build this network systematically, not reactively.',
    phase: 1,
    default_week: 3,
    category: 'Relationships',
    priority: 'critical',
    start_week: 2,
    end_week: 13,
    watkins_groups: ['Create Alliances'],
    depth: 0,
  },
  {
    id: 'map-influential-players',
    title: 'Map influential players across the organisation',
    description: 'Build a map of the informal power structure — who has real influence beyond formal authority.',
    detail: 'Build a map of the informal power structure — who has real influence beyond their formal authority? Who are the connectors, the gatekeepers, the informal advisers to senior leadership? Who has the trust of the workforce? This map will be different from the org chart. Use conversations and observation to build it — ask people who they go to when they need something done.',
    phase: 1,
    default_week: 3,
    category: 'Relationships',
    priority: 'high',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Create Alliances'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'meet-key-internal-players',
    title: 'Ensure you\'re meeting key internal players',
    description: 'Be proactive — don\'t wait for key lateral peers to seek you out.',
    detail: 'Don\'t wait for key lateral peers to seek you out — be proactive. Schedule coffees, walking meetings, or informal 1:1s with the people who matter to your success. Go into these meetings curious and relationship-focused, not transactional. You\'re investing in goodwill before you need to draw on it.',
    phase: 1,
    default_week: 3,
    category: 'Relationships',
    priority: 'high',
    start_week: 2,
    end_week: 5,
    watkins_groups: ['Create Alliances'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'map-external-players',
    title: 'Map external players',
    description: 'Build a picture of key external stakeholders and their disposition.',
    detail: 'Build a picture of the key external stakeholders — clients, funders, partners, regulators, sector bodies, peer organisations. For each: what is their relationship with your organisation? What are their interests? What is their current disposition toward you/your team? Who has relationships with them already and can help broker introductions?',
    phase: 1,
    default_week: 3,
    category: 'Relationships',
    priority: 'high',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Create Alliances'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'meet-external-players',
    title: 'Meet key external players',
    description: 'Get in front of key external stakeholders early — relationship first, not transactional.',
    detail: 'Get in front of key external stakeholders early. These meetings should feel relational, not transactional — you\'re introducing yourself, understanding their priorities, and beginning to build trust. Avoid making commitments until you have a firm strategy. Listen more than you talk.',
    phase: 1,
    default_week: 5,
    category: 'Relationships',
    priority: 'high',
    start_week: 3,
    end_week: 7,
    watkins_groups: ['Create Alliances'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'identify-supporters-early-wins',
    title: 'Identify supporters for early wins',
    description: 'Map who you need support from for each early win project and what kind.',
    detail: 'For each early win project you\'re pursuing, map who you need support from and what kind of support. Be specific: you need X person to approve Y, or Z team to contribute resource to W. Identify any potential blockers and understand their objections — often resistance comes from fear of looking incompetent, discomfort with change, or threats to existing power. Address these proactively rather than steamrolling.',
    phase: 2,
    default_week: 5,
    category: 'Relationships',
    priority: 'high',
    start_week: 5,
    end_week: 5,
    watkins_groups: ['Create Alliances', 'Secure Early Wins'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'secure-support-early-wins',
    title: 'Secure support for early wins',
    description: 'Actively work to build support for your early win initiatives.',
    detail: 'Actively work to build support for your early win initiatives. Unpack opposition: listen to why people are resistant — are they attached to the status quo? Uncomfortable with the change? Worried about looking incompetent? Threatened in terms of power or allies? Address each type of resistance differently. Don\'t try to force through initiatives without sufficient support — the cost in relationship capital is usually not worth it.',
    phase: 2,
    default_week: 6,
    category: 'Relationships',
    priority: 'high',
    start_week: 6,
    end_week: 7,
    watkins_groups: ['Create Alliances', 'Secure Early Wins'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'identify-supporters-strategy',
    title: 'Identify supporters for your strategy',
    description: 'Build a coalition map — who you need, who could block, and what would move them.',
    detail: 'Build a coalition for your strategic direction. Who are the key people whose support you need to make the strategy succeed? Who are the potential blockers? Map each key player: their current position (supporter/neutral/resistant), their interests, and what would move them toward support. A strategy without a coalition is just a document.',
    phase: 2,
    default_week: 6,
    category: 'Relationships',
    priority: 'high',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Create Alliances', 'Achieve Alignment'],
    parent_id: 'group-alliances',
    depth: 1,
  },
  {
    id: 'secure-support-strategy',
    title: 'Secure support for your strategy',
    description: 'Systematically build the coalition you need to make the strategy succeed.',
    detail: 'Systematically build the coalition you need. For supporters: keep them engaged, give them visibility, make them co-owners of the strategy. For neutrals: find the version of the strategy that addresses their interests. For resisters: understand their objections, address them where legitimate, isolate them where not. This is ongoing work throughout your first quarter and beyond.',
    phase: 2,
    default_week: 7,
    category: 'Relationships',
    priority: 'high',
    start_week: 5,
    end_week: 13,
    watkins_groups: ['Create Alliances', 'Achieve Alignment'],
    parent_id: 'group-alliances',
    depth: 1,
  },


  // ─── RECURRING: WEEKLY REVIEW ─────────────────────────────────────────────

  {
    id: 'weekly-review',
    title: 'Weekly Review',
    description: 'Structured end-of-week reflection — consolidate learning across all Watkins dimensions.',
    detail: 'Weekly cadence, weeks 1–13. Review meetings from the week — pull out key points on: people, influence networks, early wins, strategy. Plan for next week. Weekly review questions: People — What have I learned about people this week? Who has impressed me? Who has concerned me? Influence network — How is my network developing? Where are the gaps? Learning — What are the key things I\'ve learned? Where are the remaining gaps? Diagnosis and strategy — How is my diagnosis developing? Have I learned anything that changes my view? Self — How am I doing internally? Am I excited? Confident? In control? What has bothered me? What has gone well? What has gone poorly? Plan — What are my priorities for next week?',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'critical',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Manage Yourself', 'Accelerate Your Learning'],
    depth: 0,
  },

  // ─── RECURRING: MONTHLY REVIEWS ──────────────────────────────────────────

  {
    id: 'monthly-review-m1',
    title: 'Monthly Review — Month 1',
    description: 'Deeper structured review at the end of Month 1 — looking back and planning ahead.',
    detail: 'Review your progress on each of the Watkins dimensions: Prepare and manage yourself — Are you adopting the right mindset? Have you genuinely let go of your previous role? Accelerate your learning — Are you learning fast enough? Do you know what you need to learn and from whom? Match strategy to situation — Are you being systematic in your diagnosis? Negotiate success — Are you building the right relationships with your boss? Secure early wins — Are the things you\'re pursuing genuinely important? Achieve alignment — Are you identifying and fixing misalignments? Build your team — Are you assessing your team rigorously? Create alliances — Is your network developing? Then set your plan for Month 2: What are the 3–5 most important things you will do? What decisions need to be made? What conversations need to happen? What do you need from your boss?',
    phase: 1,
    default_week: 4,
    category: 'Self',
    priority: 'critical',
    start_week: 4,
    end_week: 4,
    watkins_groups: ['Manage Yourself', 'Accelerate Your Learning'],
    depth: 0,
  },
  {
    id: 'monthly-review-m2',
    title: 'Monthly Review — Month 2',
    description: 'Deeper structured review at the end of Month 2 — looking back and planning ahead.',
    detail: 'Review your progress on each of the Watkins dimensions: Prepare and manage yourself — Are you managing your energy and stress effectively? Are you building the right habits? Accelerate your learning — Are there gaps in your understanding you\'ve been avoiding? Match strategy to situation — Are you developing and consulting on options? Are you thinking carefully about how to lead change? Negotiate success — Are you managing expectations effectively? Do you understand what your boss wants? Secure early wins — Are you building credibility without creating dependencies? Achieve alignment — Are you moving at the right pace? Build your team — Are you making the personnel decisions that need to be made? Create alliances — Are you building genuine relationships or just transactional ones? Then set your plan for Month 3.',
    phase: 2,
    default_week: 8,
    category: 'Self',
    priority: 'critical',
    start_week: 8,
    end_week: 8,
    watkins_groups: ['Manage Yourself', 'Accelerate Your Learning'],
    depth: 0,
  },
  {
    id: 'monthly-review-m3',
    title: 'Monthly Review — Month 3',
    description: 'Deeper structured review at the end of Month 3 — quarter review and quarter 2 planning.',
    detail: 'Review your progress on each of the Watkins dimensions for the full first quarter: Prepare and manage yourself — Have you genuinely let go of your previous role and adopted the right mindset for this one? Accelerate your learning — Do you now have the picture you need to lead effectively? Match strategy to situation — Have you systematically diagnosed the situation and developed options? Negotiate success — Have you built the right relationships and managed expectations with your boss? Secure early wins — Have you built credibility through genuine, visible wins? Achieve alignment — Have you identified and addressed misalignments in strategy, structure, processes, and capability? Build your team — Have you made the personnel decisions that needed making? Create alliances — Do you have the coalition you need for quarter 2? Set your plan for Quarter 2.',
    phase: 3,
    default_week: 13,
    category: 'Self',
    priority: 'critical',
    start_week: 13,
    end_week: 13,
    watkins_groups: ['Manage Yourself', 'Accelerate Your Learning', 'Achieve Alignment'],
    depth: 0,
  },
];
