export type LeaderLevel = 'ic' | 'team_lead' | 'manager' | 'director' | 'executive';

export interface ChecklistItemDef {
  id: string;
  title: string;
  description: string;
  detail: string;
  phase: 1 | 2 | 3;
  default_week: number;
  default_day?: number;
  category: string;
  priority: 'critical' | 'high' | 'normal';
  relevant_levels?: LeaderLevel[];
  start_week: number;
  end_week: number;
  watkins_groups: string[];
  parent_id?: string;
  depth: number;
  sub_activity?: string;
}

export const CHECKLIST_ITEMS: ChecklistItemDef[] = [
  // ─── WATKINS GROUP 1: PREPARE YOURSELF (Week 0) ───
  {
    id: 'prepare-0',
    title: 'Prepare for your transition',
    description: 'Complete all pre-start preparation before Day 1 so you arrive focused and ready.',
    detail: '• These are things you can do with NO access, NO authority, NO insider knowledge\n• Complete all items before your first day\n• The goal is to maximise cognitive bandwidth and reduce friction\n• Preparation compounds — every hour invested here saves days later',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'critical',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself'],
    depth: 0,
  },
  {
    id: 'prepare-1',
    title: 'Mentally close out your previous role',
    description: 'Consciously draw a line under your last job before starting the new one.',
    detail: '• Reflect on what you achieved, learned, and are leaving behind\n• Write a short note to yourself summarising your last role — this helps create psychological closure\n• Identify habits or approaches from your last role that may NOT serve you in the new one\n• Resist the urge to keep solving problems from your old role during your notice period',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'critical',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Manage Yourself'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-2',
    title: 'Research the organisation from public sources',
    description: 'Build a picture from what\'s publicly available before you have insider access.',
    detail: '• Read the annual report, strategy documents, and recent press coverage\n• Check Glassdoor/employee reviews for cultural signals\n• Look at LinkedIn profiles of your future team and key stakeholders\n• Note 5 questions these sources raise that you\'ll investigate from the inside',
    phase: 1,
    default_week: 0,
    category: 'Strategy',
    priority: 'high',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Accelerate Your Learning'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-3',
    title: 'Read or re-read your transition framework',
    description: 'Ground yourself in evidence-based transition research before day 1.',
    detail: '• Read or re-read The First 90 Days (Watkins) — focus on the STARS model and 5 conversations\n• Note which chapters feel most relevant to your specific situation\n• Consider also: "The New Leader\'s 100-Day Action Plan" (Bradt) for pre-start specifics',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'high',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-4',
    title: 'Sort practical logistics',
    description: 'Remove friction from Day 1 so you can focus on people, not admin.',
    detail: '• Confirm commute route, office location, building access\n• Find out who your PA/EA is (if you have one) and introduce yourself\n• Confirm IT setup timelines — laptop, email, systems access\n• Plan your first-day outfit and route (trivial but reduces anxiety)',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'normal',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-5',
    title: 'Clear your personal plate',
    description: 'Maximise cognitive bandwidth for the new role.',
    detail: '• Book health appointments, deal with domestic admin\n• Sort anything that will compete for attention in week 1\n• Consider batch-cooking meals or simplifying your routine for the first 2 weeks\n• Tell close friends/family you\'ll be less available initially',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'high',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Manage Yourself'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-6',
    title: 'Have any pre-start conversations you\'ve been invited to',
    description: 'If your new boss or HR suggests a pre-start meeting, take it — but listen more than you talk.',
    detail: '• Accept any offered pre-start coffee/call with your boss\n• Listen for signals about expectations, culture, and priorities\n• Don\'t try to start the job early — just build rapport\n• Note 3 things you learn from this conversation',
    phase: 1,
    default_week: 0,
    category: 'Boss',
    priority: 'normal',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Negotiate Success'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-7',
    title: 'Plan your Day 1 introduction',
    description: 'Prepare a brief, authentic self-introduction.',
    detail: '• Draft a 60-second intro: who you are, why you\'re excited, what you want to learn\n• Don\'t overpromise or set an agenda on day 1\n• Plan to spend Day 1 listening and meeting people, not making decisions\n• Consider the tone you want to set — curious, collaborative, calm',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'normal',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself'],
    parent_id: 'prepare-0',
    depth: 1,
  },
  {
    id: 'prepare-8',
    title: 'Write down your 5 biggest questions',
    description: 'Create your initial learning agenda.',
    detail: '• What are the 5 things you most need to understand in month 1?\n• These become your structured learning agenda for weeks 1-4\n• Include questions about: strategy, team, culture, stakeholders, resources\n• You\'ll refine these once you\'re inside — this is a starting point',
    phase: 1,
    default_week: 0,
    category: 'Self',
    priority: 'critical',
    start_week: 0,
    end_week: 0,
    watkins_groups: ['Prepare Yourself', 'Accelerate Your Learning'],
    parent_id: 'prepare-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 2: ACCELERATE YOUR LEARNING (Weeks 1–4) ───
  {
    id: 'learn-0',
    title: 'Accelerate your learning',
    description: 'Gather information, understand context, culture, and stakeholders in your first month.',
    detail: '• Structure your first weeks around listening, not doing\n• Use consistent questions across conversations for pattern-matching\n• Document what you learn and how your understanding evolves\n• Synthesise and share findings by week 4',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 4,
    watkins_groups: ['Accelerate Your Learning'],
    depth: 0,
  },
  {
    id: 'learn-1',
    title: 'Design your listening tour',
    description: 'Structure your first 2 weeks around listening, not doing.',
    detail: '• Schedule 1:1s with all direct reports in week 1\n• Schedule meetings with key stakeholders in weeks 1-2\n• Prepare a consistent set of questions to ask everyone (allows pattern-matching)\n• Ask everyone: "What would you do if you were in my position?"',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'critical',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-2',
    title: 'Conduct 1:1s with all direct reports',
    description: 'Meet every direct report individually. Listen first.',
    detail: '• Ask about their role, priorities, frustrations, and what they\'d change\n• Ask what\'s working well and what isn\'t\n• Ask about the team dynamics and culture\n• Take notes — you\'ll want to compare what different people say',
    phase: 1,
    default_week: 1,
    category: 'Team',
    priority: 'critical',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Build Your Team'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-3',
    title: 'Map the informal power structure',
    description: 'Identify who really influences decisions, beyond the org chart.',
    detail: '• Ask: "Who do people go to when they need something done?"\n• Note who gets mentioned repeatedly across your conversations\n• Identify the "institutional historians" who understand the unwritten rules\n• Map: formal authority vs. informal influence — they rarely match',
    phase: 1,
    default_week: 2,
    category: 'Stakeholders',
    priority: 'high',
    start_week: 1,
    end_week: 3,
    watkins_groups: ['Accelerate Your Learning', 'Create Alliances'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-4',
    title: 'Review existing strategy and data',
    description: 'Read the documents that shaped the current direction.',
    detail: '• Review the current strategy document, business plan, and recent board papers\n• Look at financial and operational data — revenue, costs, KPIs, trends\n• Read the last 2-3 team meeting notes or away-day outputs\n• Note where the stated strategy and actual activity seem misaligned',
    phase: 1,
    default_week: 1,
    category: 'Strategy',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Accelerate Your Learning', 'Match Strategy to Situation'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-5',
    title: 'Conduct cross-functional stakeholder interviews',
    description: 'Talk to people outside your immediate team.',
    detail: '• Interview peers in adjacent teams — what do they need from your team?\n• Talk to internal "customers" of your team\'s work\n• Ask external stakeholders (clients, partners) for their perspective\n• Collect intelligence on how your team is perceived',
    phase: 1,
    default_week: 3,
    category: 'Stakeholders',
    priority: 'high',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Accelerate Your Learning', 'Create Alliances'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-6',
    title: 'Synthesise and share preliminary findings',
    description: 'Pull together what you\'ve learned and test it.',
    detail: '• Write a 1-page summary of what you\'ve heard and what patterns you see\n• Share it with your boss — "Here\'s what I\'m hearing. Does this ring true?"\n• Share a version with your team — this shows you\'ve listened\n• Identify the 3 biggest surprises vs. your pre-start assumptions',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 3,
    end_week: 4,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'learn-0',
    depth: 1,
  },
  {
    id: 'learn-7',
    title: 'Document your evolving hypotheses',
    description: 'Track how your understanding develops.',
    detail: '• Keep a running document of "what I think is true" — update weekly\n• Note where your hypotheses have been confirmed or contradicted\n• This becomes raw material for your STARS diagnosis and 90-day plan',
    phase: 1,
    default_week: 2,
    category: 'Self',
    priority: 'normal',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Accelerate Your Learning'],
    parent_id: 'learn-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 3: MATCH STRATEGY TO SITUATION (Weeks 2–5) ───
  {
    id: 'situation-0',
    title: 'Diagnose the situation',
    description: 'Use the STARS framework to diagnose your context and adapt your approach accordingly.',
    detail: '• STARS: Startup, Turnaround, Accelerated growth, Realignment, Sustaining success\n• Different situations require radically different leadership approaches\n• Most roles are a mix — diagnose at multiple levels\n• Your diagnosis shapes your entire 90-day plan',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'critical',
    start_week: 2,
    end_week: 5,
    watkins_groups: ['Match Strategy to Situation'],
    depth: 0,
  },
  {
    id: 'situation-1',
    title: 'Complete a STARS diagnostic',
    description: 'Determine which STARS situation you\'re in — it changes everything.',
    detail: '• STARS: Startup, Turnaround, Accelerated growth, Realignment, Sustaining success\n• Different situations require radically different leadership approaches\n• Most roles are a mix — your team might be Realignment while the org is Sustaining\n• Discuss your diagnosis with your boss — do they agree?',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'critical',
    start_week: 3,
    end_week: 4,
    watkins_groups: ['Match Strategy to Situation'],
    parent_id: 'situation-0',
    depth: 1,
  },
  {
    id: 'situation-2',
    title: 'Identify your leadership style defaults and STARS mismatches',
    description: 'Your instincts from your last role may not fit this one.',
    detail: '• What\'s your default approach? (Action-oriented? Consensus-building? Analytical?)\n• Does that match the STARS situation? (Turnarounds need decisive action; Realignments need coalition-building)\n• Identify 2-3 specific behaviours you need to adapt\n• Ask trusted advisors for feedback on your style',
    phase: 1,
    default_week: 3,
    category: 'Self',
    priority: 'high',
    start_week: 3,
    end_week: 4,
    watkins_groups: ['Match Strategy to Situation', 'Manage Yourself'],
    parent_id: 'situation-0',
    depth: 1,
  },
  {
    id: 'situation-3',
    title: 'Define the implications for your 90-day approach',
    description: 'Translate your diagnosis into a concrete plan.',
    detail: '• Based on STARS, what should you prioritise in months 2-3?\n• What should you explicitly NOT do? (This is as important as what you do)\n• Write a 1-page "My 90-Day Approach" document\n• Review with your boss for alignment',
    phase: 1,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 4,
    end_week: 5,
    watkins_groups: ['Match Strategy to Situation'],
    parent_id: 'situation-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 4: NEGOTIATE SUCCESS (Weeks 1–8) ───
  {
    id: 'negotiate-0',
    title: 'Build the relationship with your boss',
    description: 'Run the five critical boss conversations in sequence to align on expectations, resources, and style.',
    detail: '• Watkins identifies 5 critical conversations with your boss\n• They must happen in the right sequence\n• Regular check-ins prevent misalignment from building up\n• This relationship is the single most important factor in your success',
    phase: 1,
    default_week: 1,
    category: 'Boss',
    priority: 'critical',
    start_week: 1,
    end_week: 8,
    watkins_groups: ['Negotiate Success'],
    depth: 0,
  },
  {
    id: 'negotiate-1',
    title: 'Boss conversation 1: Situational diagnosis',
    description: 'Your first substantive conversation with your boss — understand how they see the situation.',
    detail: '• Ask: "How do you see the situation I\'m walking into?"\n• Ask: "What are the real challenges and opportunities?"\n• Listen carefully — does their view match what you\'re hearing from others?\n• Note any gaps between their view and reality as seen by the team',
    phase: 1,
    default_week: 1,
    category: 'Boss',
    priority: 'critical',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-2',
    title: 'Boss conversation 2: Expectations',
    description: 'Get explicit about what success looks like.',
    detail: '• Ask: "What does success look like at 30, 60, and 90 days?"\n• Ask: "What would make you worried at the 6-month mark?"\n• Write down the agreed success metrics and share them back\n• If expectations are unrealistic, push back now — not later',
    phase: 1,
    default_week: 2,
    category: 'Boss',
    priority: 'critical',
    start_week: 2,
    end_week: 3,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-3',
    title: 'Boss conversation 3: Resources',
    description: 'Understand what you have to work with — budget, people, authority.',
    detail: '• Ask: "What budget and headcount do I control?"\n• Ask: "What resources can I request beyond my direct allocation?"\n• Ask: "Where are the constraints I should know about?"\n• Negotiate for what you need — it\'s easier to get resources early than later',
    phase: 2,
    default_week: 5,
    category: 'Boss',
    priority: 'high',
    start_week: 5,
    end_week: 6,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-4',
    title: 'Boss conversation 4: Working style',
    description: 'Align on how you\'ll work together day-to-day.',
    detail: '• Ask: "How do you prefer to communicate — email, Slack, in-person?"\n• Ask: "How often do you want updates, and in what format?"\n• Ask: "What decisions do you want to be involved in vs. delegated?"\n• Establish a standing 1:1 cadence (weekly or fortnightly)',
    phase: 1,
    default_week: 3,
    category: 'Boss',
    priority: 'high',
    start_week: 3,
    end_week: 4,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-5',
    title: 'Boss conversation 5: Personal development',
    description: 'What should you focus on growing as a leader?',
    detail: '• Ask: "What development areas should I be working on?"\n• Ask: "What feedback have you heard about me from others?"\n• Discuss what support is available (coaching, mentoring, training)\n• This conversation signals self-awareness and openness',
    phase: 2,
    default_week: 7,
    category: 'Boss',
    priority: 'normal',
    start_week: 7,
    end_week: 8,
    watkins_groups: ['Negotiate Success', 'Manage Yourself'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-6',
    title: 'Establish a standing 1:1 with your manager',
    description: 'Regular check-ins prevent misalignment from building up.',
    detail: '• Set up a recurring weekly or fortnightly meeting\n• Use the first few to build the relationship, not just report progress\n• Always come prepared — agenda, updates, questions\n• Flag early any signs that expectations are shifting',
    phase: 1,
    default_week: 2,
    category: 'Boss',
    priority: 'critical',
    start_week: 2,
    end_week: 3,
    watkins_groups: ['Negotiate Success'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-7',
    title: 'Day 30 check-in with your boss',
    description: 'Formal 30-day review — how is it going?',
    detail: '• Share your preliminary findings and STARS diagnosis\n• Review the 30/60/90 metrics agreed in conversation 2\n• Ask: "Am I focused on the right things?"\n• Adjust your plan based on feedback',
    phase: 1,
    default_week: 4,
    category: 'Boss',
    priority: 'high',
    start_week: 4,
    end_week: 4,
    watkins_groups: ['Negotiate Success', 'Manage Yourself'],
    parent_id: 'negotiate-0',
    depth: 1,
  },
  {
    id: 'negotiate-8',
    title: 'Day 60 milestone review',
    description: 'Midpoint accountability check.',
    detail: '• Present your 30-60 day report (wins, challenges, team assessment)\n• Review progress against agreed metrics\n• Discuss what needs to change for the final 30 days\n• Re-negotiate resources or priorities if needed',
    phase: 2,
    default_week: 8,
    category: 'Boss',
    priority: 'high',
    start_week: 8,
    end_week: 8,
    watkins_groups: ['Negotiate Success', 'Manage Yourself'],
    parent_id: 'negotiate-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 5: SECURE EARLY WINS (Weeks 3–7) ───
  {
    id: 'wins-0',
    title: 'Secure early wins',
    description: 'Identify and deliver quick credibility-building victories in your first two months.',
    detail: '• Early wins build trust, credibility, and momentum\n• The best wins are visible, team-owned, and connected to strategy\n• Frame wins as "we" achievements, not "I" achievements\n• Connect each win to the bigger picture you\'re building',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'critical',
    start_week: 3,
    end_week: 7,
    watkins_groups: ['Secure Early Wins'],
    depth: 0,
  },
  {
    id: 'wins-1',
    title: 'Identify 2-3 early win targets',
    description: 'Find quick victories that build credibility.',
    detail: '• Look for longstanding frustrations that are quick to fix\n• Ideal early win: visible, team-owned, demonstrates you\'ve listened\n• Avoid wins that are purely personal — they must benefit the team\n• Check with your boss: "Would this be a good early focus?"',
    phase: 1,
    default_week: 3,
    category: 'Strategy',
    priority: 'critical',
    start_week: 3,
    end_week: 3,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'wins-0',
    depth: 1,
  },
  {
    id: 'wins-2',
    title: 'Frame early wins as team initiatives',
    description: 'Credit the team, not yourself — this builds trust.',
    detail: '• Position wins as "we" achievements, not "I" achievements\n• Involve the team in identifying and delivering the win\n• Give specific, public credit to individuals who contributed\n• This signals a collaborative leadership style from day 1',
    phase: 1,
    default_week: 3,
    category: 'Team',
    priority: 'high',
    start_week: 3,
    end_week: 4,
    watkins_groups: ['Secure Early Wins', 'Build Your Team'],
    parent_id: 'wins-0',
    depth: 1,
  },
  {
    id: 'wins-3',
    title: 'Deliver your first early win',
    description: 'Ship something. Make visible progress.',
    detail: '• Solve a specific, concrete problem that people care about\n• Communicate what changed and why\n• Connect the win to your broader vision\n• Note the reaction — did it land well? What did you learn?',
    phase: 2,
    default_week: 5,
    category: 'Strategy',
    priority: 'critical',
    start_week: 5,
    end_week: 5,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'wins-0',
    depth: 1,
  },
  {
    id: 'wins-4',
    title: 'Deliver a second early win',
    description: 'Build momentum with a second visible achievement.',
    detail: '• This one should be in a different area from win #1 (shows breadth)\n• Ideally addresses a different stakeholder group\n• Again: team-owned, visible, connected to strategy',
    phase: 2,
    default_week: 7,
    category: 'Strategy',
    priority: 'high',
    start_week: 7,
    end_week: 7,
    watkins_groups: ['Secure Early Wins'],
    parent_id: 'wins-0',
    depth: 1,
  },
  {
    id: 'wins-5',
    title: 'Connect wins to strategic narrative',
    description: 'Early wins should point toward the bigger picture.',
    detail: '• Explain HOW this win fits the longer-term direction\n• This transitions you from "quick fixes" to "strategic leadership"\n• Use wins as evidence in stakeholder conversations: "We\'ve already shown we can..."',
    phase: 2,
    default_week: 6,
    category: 'Strategy',
    priority: 'normal',
    start_week: 5,
    end_week: 7,
    watkins_groups: ['Secure Early Wins', 'Achieve Alignment'],
    parent_id: 'wins-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 6: ACHIEVE ALIGNMENT (Weeks 4–10) ───
  {
    id: 'align-0',
    title: 'Achieve strategic alignment',
    description: 'Align vision, strategic priorities, org structure, and decision rights.',
    detail: '• Use Watkins\' 5-element model: Strategy → Structure → Processes → Skills → Culture\n• Look for misalignments between stated strategy and actual activity\n• Narrow focus to 3-5 clear priorities everyone can articulate\n• Build a roadmap for changes that extend beyond 90 days',
    phase: 2,
    default_week: 5,
    category: 'Strategy',
    priority: 'critical',
    start_week: 4,
    end_week: 10,
    watkins_groups: ['Achieve Alignment'],
    depth: 0,
  },
  {
    id: 'align-1',
    title: 'Conduct a strategic alignment diagnostic',
    description: 'Assess whether strategy, structure, processes, people, and culture are aligned.',
    detail: '• Watkins\' 5-element model: Strategy → Structure → Processes → Skills → Culture\n• Look for misalignments: strategy says X but structure supports Y\n• Talk to 5-10 people across levels: "What\'s getting in the way?"\n• Identify the 3 biggest misalignments',
    phase: 2,
    default_week: 4,
    category: 'Strategy',
    priority: 'high',
    start_week: 4,
    end_week: 5,
    watkins_groups: ['Achieve Alignment'],
    parent_id: 'align-0',
    depth: 1,
  },
  {
    id: 'align-2',
    title: 'Clarify the strategic priorities',
    description: 'Get to 3-5 clear priorities everyone can articulate.',
    detail: '• If there are more than 5 priorities, there are no priorities\n• Test: can every team member name the top 3? If not, they\'re not clear enough\n• Align these with your boss\'s expectations (from conversation 2)\n• Write them down simply — post them visibly',
    phase: 2,
    default_week: 5,
    category: 'Strategy',
    priority: 'high',
    start_week: 5,
    end_week: 6,
    watkins_groups: ['Achieve Alignment'],
    parent_id: 'align-0',
    depth: 1,
  },
  {
    id: 'align-3',
    title: 'Audit decision-making and governance',
    description: 'Understand how decisions actually get made (vs. how they\'re supposed to).',
    detail: '• Map your decision rights explicitly — what can you decide alone?\n• Identify decision bottlenecks — where do things stall?\n• Clarify governance: what needs board/committee approval?\n• Make quick-win structural clarifications where you can',
    phase: 2,
    default_week: 7,
    category: 'Strategy',
    priority: 'normal',
    start_week: 6,
    end_week: 8,
    watkins_groups: ['Achieve Alignment'],
    parent_id: 'align-0',
    depth: 1,
  },
  {
    id: 'align-4',
    title: 'Align team on vision and goals',
    description: 'Get your team pulling in the same direction.',
    detail: '• Run a team session: "Here\'s what I\'ve heard, here\'s where I think we should go"\n• Test your strategic priorities with the team — do they make sense from their perspective?\n• Co-create team objectives that cascade from the strategic priorities\n• Document and circulate — no ambiguity',
    phase: 2,
    default_week: 7,
    category: 'Team',
    priority: 'high',
    start_week: 6,
    end_week: 8,
    watkins_groups: ['Achieve Alignment', 'Build Your Team'],
    parent_id: 'align-0',
    depth: 1,
  },
  {
    id: 'align-5',
    title: 'Build a 12-month alignment roadmap',
    description: 'Plan beyond the 90 days — what structural changes are needed?',
    detail: '• Identify changes needed to structure, processes, or governance\n• Sequence them realistically — not everything can change at once\n• Get boss approval before announcing structural changes\n• Share the roadmap with stakeholders for buy-in',
    phase: 3,
    default_week: 9,
    category: 'Strategy',
    priority: 'normal',
    start_week: 8,
    end_week: 10,
    watkins_groups: ['Achieve Alignment'],
    parent_id: 'align-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 7: BUILD YOUR TEAM (Weeks 1–8) ───
  {
    id: 'team-0',
    title: 'Build your team',
    description: 'Assess capability, have career and performance conversations, shape team culture.',
    detail: '• Understand what you have before deciding what needs to change\n• Give people meaningful assignments that reveal capability\n• Address underperformance early — it doesn\'t improve with time\n• Build the team you want to lead, not just manage what you inherited',
    phase: 1,
    default_week: 2,
    category: 'Team',
    priority: 'critical',
    start_week: 1,
    end_week: 8,
    watkins_groups: ['Build Your Team'],
    depth: 0,
  },
  {
    id: 'team-1',
    title: 'Assess team capability and performance',
    description: 'Understand what you have before you decide what needs to change.',
    detail: '• Create individual assessment profiles: competence, motivation, alignment\n• Use Watkins\' keep/develop/replace framework (but don\'t rush to "replace")\n• Get multiple data points — don\'t rely on first impressions\n• Give meaningful assignments that reveal capability',
    phase: 1,
    default_week: 3,
    category: 'Team',
    priority: 'critical',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Build Your Team'],
    parent_id: 'team-0',
    depth: 1,
  },
  {
    id: 'team-2',
    title: 'Have career conversations with each direct report',
    description: 'Understand what each person wants, not just what they do.',
    detail: '• Ask: "What do you want from this role? Where do you want to be in 2 years?"\n• Ask: "What support do you need from me?"\n• Listen for alignment (or misalignment) with the team\'s direction\n• This builds trust and gives you data for team decisions',
    phase: 1,
    default_week: 4,
    category: 'Team',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Build Your Team'],
    parent_id: 'team-0',
    depth: 1,
  },
  {
    id: 'team-3',
    title: 'Have performance conversations where needed',
    description: 'Address underperformance early — it doesn\'t get better with time.',
    detail: '• Be specific: behaviour, impact, expectation\n• Offer support — but be clear about the required standard\n• Document the conversation\n• Follow up within 2 weeks',
    phase: 2,
    default_week: 5,
    category: 'Team',
    priority: 'high',
    start_week: 5,
    end_week: 6,
    watkins_groups: ['Build Your Team'],
    parent_id: 'team-0',
    depth: 1,
  },
  {
    id: 'team-4',
    title: 'Make and communicate team structure decisions by Day 60',
    description: 'If changes are needed, make them in month 2 — not month 3+.',
    detail: '• Watkins: restructuring after day 60 is often too late\n• If someone needs to move, it\'s better done decisively with dignity\n• Communicate changes clearly — explain the why\n• Support the team through the transition (even if they agree with the decision)',
    phase: 2,
    default_week: 7,
    category: 'Team',
    priority: 'high',
    start_week: 6,
    end_week: 8,
    watkins_groups: ['Build Your Team'],
    parent_id: 'team-0',
    depth: 1,
  },
  {
    id: 'team-5',
    title: 'Invest in team cohesion and culture',
    description: 'Build the team you want to lead, not just manage what you inherited.',
    detail: '• Establish team norms: how do we communicate, decide, disagree?\n• Create space for the team to gel — off-sites, team lunches, shared goals\n• Identify and develop your high performers — they\'re your future\n• Model the culture you want: if you want openness, be open',
    phase: 2,
    default_week: 6,
    category: 'Team',
    priority: 'normal',
    start_week: 4,
    end_week: 8,
    watkins_groups: ['Build Your Team'],
    parent_id: 'team-0',
    depth: 1,
  },
  {
    id: 'team-6',
    title: 'Identify high performers who need urgent investment',
    description: 'Your best people are also the most at risk of leaving if they feel neglected.',
    detail: '• Identify your top 2-3 performers in the first month\n• Have explicit conversations: "I see your contribution. Here\'s how I want to support you."\n• Give them stretch opportunities early — shows you value them\n• Retention of top talent is one of the highest-value things you can do in month 1',
    phase: 1,
    default_week: 4,
    category: 'Team',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Build Your Team', 'Accelerate Everyone'],
    parent_id: 'team-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 8: CREATE ALLIANCES (Weeks 1–10) ───
  {
    id: 'alliances-0',
    title: 'Create alliances and coalitions',
    description: 'Map stakeholders, build lateral relationships, and create coalition support for your agenda.',
    detail: '• Your peers are as important as your boss and team\n• Map influence and alignment — they rarely match the org chart\n• Invest disproportionately in the 3 people who can make or break your agenda\n• Build coalitions on shared goals, not reciprocal favours',
    phase: 1,
    default_week: 2,
    category: 'Stakeholders',
    priority: 'critical',
    start_week: 1,
    end_week: 10,
    watkins_groups: ['Create Alliances'],
    depth: 0,
  },
  {
    id: 'alliances-1',
    title: 'Build a stakeholder influence map',
    description: 'Map who matters, who supports you, and who might block you.',
    detail: '• Use HBR\'s 2x2: Influence (high/low) × Alignment (supportive/resistant)\n• Four quadrants: Champions, Opponents, Supporters, Blockers\n• Focus energy on converting Opponents to Champions\n• Keep Champions engaged — don\'t neglect your allies',
    phase: 1,
    default_week: 2,
    category: 'Stakeholders',
    priority: 'critical',
    start_week: 1,
    end_week: 3,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },
  {
    id: 'alliances-2',
    title: 'Schedule 1:1s with all key lateral stakeholders',
    description: 'Your peers are as important as your boss and team.',
    detail: '• Meet every peer who your team interacts with regularly\n• Ask: "What does my team do well? What could be better?"\n• Look for opportunities to help THEM — reciprocity builds alliances\n• McKinsey: successful leaders spend 30-40% of first 90 days on relationship-building',
    phase: 1,
    default_week: 3,
    category: 'Stakeholders',
    priority: 'high',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },
  {
    id: 'alliances-3',
    title: 'Identify your 3 pivotal coalition members',
    description: 'Find the 3 people who can make or break your agenda.',
    detail: '• These are people with influence AND willingness to support change\n• Invest heavily in these relationships — they amplify your impact\n• Test your ideas with them before going public\n• They become your "early warning system" for political dynamics',
    phase: 1,
    default_week: 4,
    category: 'Stakeholders',
    priority: 'high',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },
  {
    id: 'alliances-4',
    title: 'Map potential blocking coalitions',
    description: 'Understand where resistance will come from.',
    detail: '• Who benefits from the status quo? They\'ll resist change\n• Who has been passed over or feels threatened by your arrival?\n• Don\'t try to defeat blockers — try to find shared interests\n• If you can\'t convert them, at least neutralise their opposition',
    phase: 1,
    default_week: 4,
    category: 'Stakeholders',
    priority: 'normal',
    start_week: 3,
    end_week: 5,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },
  {
    id: 'alliances-5',
    title: 'Build one key lateral peer relationship',
    description: 'One strong peer relationship is worth more than many shallow ones.',
    detail: '• Identify a peer who is well-connected and well-respected\n• Invest genuine time — not just transactional meetings\n• Offer value: share information, collaborate on a joint initiative\n• This becomes your "inside track" on the organisation',
    phase: 2,
    default_week: 5,
    category: 'Stakeholders',
    priority: 'normal',
    start_week: 4,
    end_week: 6,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },
  {
    id: 'alliances-6',
    title: 'Strengthen wider stakeholder network',
    description: 'Expand beyond your immediate circle in month 2-3.',
    detail: '• Identify 5-10 people you should know but haven\'t met yet\n• Attend cross-functional meetings and events\n• Establish regular rhythm with key external stakeholders (if applicable)\n• Build a reputation as someone who connects across boundaries',
    phase: 2,
    default_week: 8,
    category: 'Stakeholders',
    priority: 'normal',
    start_week: 7,
    end_week: 10,
    watkins_groups: ['Create Alliances'],
    parent_id: 'alliances-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 9: MANAGE YOURSELF (Weeks 1–13) ───
  {
    id: 'self-0',
    title: 'Manage yourself through the transition',
    description: 'Reflection, energy management, advice-seeking, and work-life boundaries throughout your first 90 days.',
    detail: '• Transitions are inherently stressful — plan for it\n• Protect your recovery practices with the same rigour as business meetings\n• Schedule weekly reflection time — 30 minutes to think, not do\n• Find an external sounding board who isn\'t inside the system',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'critical',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Manage Yourself'],
    depth: 0,
  },
  {
    id: 'self-1',
    title: 'Identify your personal stress triggers',
    description: 'Know what derails you before it happens.',
    detail: '• Transitions are inherently stressful — what are YOUR specific triggers?\n• When stressed, do you over-control? Withdraw? Get snappy?\n• Plan coping strategies in advance — exercise, sleep, boundaries\n• Tell a trusted person what to watch for',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'high',
    start_week: 1,
    end_week: 2,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },
  {
    id: 'self-2',
    title: 'Protect your recovery practices',
    description: 'The temptation to sacrifice sleep, exercise, and downtime is highest in a transition.',
    detail: '• Block non-negotiable recovery time in your calendar\n• Prioritise sleep — it\'s the single biggest factor in decision quality\n• Keep one leisure activity sacred — don\'t let work crowd out everything\n• Model sustainable working to your team',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'high',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },
  {
    id: 'self-3',
    title: 'Establish a transition advisory relationship',
    description: 'Find someone outside your organisation who can give honest feedback.',
    detail: '• This could be a mentor, coach, former boss, or trusted peer\n• Meet monthly for the first 90 days\n• Use them as a sounding board for political/strategic decisions\n• They see patterns you can\'t because they\'re not inside the system',
    phase: 1,
    default_week: 3,
    category: 'Self',
    priority: 'normal',
    start_week: 2,
    end_week: 4,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },
  {
    id: 'self-4',
    title: 'Schedule weekly reflection time',
    description: '30 minutes per week to think, not do.',
    detail: '• Block Friday afternoon or Sunday evening\n• Use the Waypoint Reflect tab prompts\n• Review: What went well? What surprised me? What would I do differently?\n• Update your learning hypotheses document',
    phase: 1,
    default_week: 1,
    category: 'Self',
    priority: 'high',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },
  {
    id: 'self-5',
    title: 'Day 30 personal reflection',
    description: 'Formal checkpoint — how are YOU doing, not just the job?',
    detail: '• Energy level: higher or lower than when you started?\n• Relationships: feeling connected or isolated?\n• Confidence: what\'s growing? What\'s shaky?\n• Write a brief "letter to myself" to read at day 90',
    phase: 1,
    default_week: 4,
    category: 'Self',
    priority: 'high',
    start_week: 4,
    end_week: 4,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },
  {
    id: 'self-6',
    title: 'Day 90 review and leadership narrative',
    description: 'Write the story of your first 90 days.',
    detail: '• What did you achieve? What surprised you? What would you do differently?\n• What\'s your leadership narrative — the story you tell about your approach?\n• What are your priorities for months 4-6?\n• Share relevant parts with your boss and team',
    phase: 3,
    default_week: 13,
    category: 'Self',
    priority: 'critical',
    start_week: 13,
    end_week: 13,
    watkins_groups: ['Manage Yourself'],
    parent_id: 'self-0',
    depth: 1,
  },

  // ─── WATKINS GROUP 10: ACCELERATE EVERYONE (Weeks 4–13) ───
  {
    id: 'everyone-0',
    title: 'Accelerate everyone around you',
    description: 'Build capability, share knowledge, coach, and delegate to lift the whole team.',
    detail: '• Model how to learn in a new role — others are watching\n• Support direct reports who are also in transition\n• Build reflection and retrospective practices into team rhythm\n• Leave a trail for the next person in your role',
    phase: 2,
    default_week: 5,
    category: 'Team',
    priority: 'normal',
    start_week: 4,
    end_week: 13,
    watkins_groups: ['Accelerate Everyone'],
    depth: 0,
  },
  {
    id: 'everyone-1',
    title: 'Share your learning approach explicitly',
    description: 'Model how to learn in a new role — others are watching.',
    detail: '• Tell your team: "Here\'s how I\'ve been approaching my first 90 days"\n• Share what surprised you and what you\'re still figuring out\n• This gives permission for others to be learners too\n• Especially powerful if you have team members also in transition',
    phase: 2,
    default_week: 4,
    category: 'Team',
    priority: 'normal',
    start_week: 4,
    end_week: 5,
    watkins_groups: ['Accelerate Everyone'],
    parent_id: 'everyone-0',
    depth: 1,
  },
  {
    id: 'everyone-2',
    title: 'Build transition support into your management cadence',
    description: 'If any of your direct reports are also new or in transition, actively support them.',
    detail: '• Ask in 1:1s: "How is your transition going? What do you need?"\n• Share frameworks and tools (like this app!) with them\n• Create a culture where transitions are taken seriously, not just survived',
    phase: 2,
    default_week: 6,
    category: 'Team',
    priority: 'normal',
    start_week: 5,
    end_week: 8,
    watkins_groups: ['Accelerate Everyone', 'Build Your Team'],
    parent_id: 'everyone-0',
    depth: 1,
  },
  {
    id: 'everyone-3',
    title: 'Establish a team retrospective practice',
    description: 'Regular reflection isn\'t just for you — build it into team practice.',
    detail: '• Monthly team retro: "What\'s working? What should we change?"\n• This creates psychological safety and continuous improvement\n• Rotate facilitation so it\'s not just your show\n• Document actions and follow up',
    phase: 2,
    default_week: 8,
    category: 'Team',
    priority: 'normal',
    start_week: 6,
    end_week: 10,
    watkins_groups: ['Accelerate Everyone'],
    parent_id: 'everyone-0',
    depth: 1,
  },
  {
    id: 'everyone-4',
    title: 'Document your onboarding experience',
    description: 'Leave a trail for the next person in this role.',
    detail: '• What do you wish someone had told you?\n• What would you change about the onboarding process?\n• Share this with HR — it improves the organisation for everyone\n• Model the behaviour you want: intellectual humility and continuous improvement',
    phase: 3,
    default_week: 11,
    category: 'Team',
    priority: 'normal',
    start_week: 10,
    end_week: 13,
    watkins_groups: ['Accelerate Everyone'],
    parent_id: 'everyone-0',
    depth: 1,
  },
  {
    id: 'everyone-5',
    title: 'Model visible intellectual humility',
    description: 'Say "I don\'t know" and "I was wrong" — it accelerates everyone\'s learning.',
    detail: '• Leaders who admit uncertainty create cultures where others feel safe to learn\n• Ask genuine questions in meetings — not rhetorical ones\n• Credit other people\'s ideas publicly\n• This is the single highest-leverage leadership behaviour in a transition',
    phase: 1,
    default_week: 1,
    category: 'Team',
    priority: 'normal',
    start_week: 1,
    end_week: 13,
    watkins_groups: ['Accelerate Everyone', 'Manage Yourself'],
    parent_id: 'everyone-0',
    depth: 1,
  },
];
